name: Create OCI instance
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  create-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install
      - name: Run script
        env:
          OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        run: php index.php
