name: Create OCI instance
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  create-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install oci
      - name: Run script
        env:
          OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        run: python main.py
